newPackage(
       "NumberFields",
    Version => "0.0.0", 
        Date => "April 7th, 2025",
        Authors => {
            {Name=>"Jack J Garzella", Email=>"jgarzell@ucsd.edu", HomePage=>"https://mathweb.ucsd.edu/~jjgarzel"},
            {Name=>"Nicholas Gaubatz", Email=>"nmg0029@auburn.edu", HomePage=>"https://nicholasgaubatz.github.io/"},
            {Name=>"Toshi Mowery", Email=>"Tosmow@gmail.com"},
            {Name => "Karl Schwede", Email=>"schwede@math.utah.edu", HomePage=>"http://www.math.utah.edu/~schwede"}
        },
        Headline => "number fields",
        Keywords => {"field extension"},
    PackageImports => {},
    PackageExports => {"PushForward", "MinimalPrimes", "InvariantRing","Permutations"},
    Reload => true,
    DebuggingMode => true
    )

export{
   "NumberField", 
   "numberField",
   "NumberFieldExtension",
   "numberFieldExtension",
   "TempNumberField",
   "tempNumberField",
   "ToshiNumberField",
   "isGalois",
   "splittingField",
   "compositums",
   "simpleExtension",
--    Merge this into compositum
   "compositumPari",
   "getRoots",
   "ringElFromMatrix",
--    "ringElFromMatrix2",
   "matrixFromRingEl",
   "matrixFromNumberFieldMap",
   "inverseNumberFieldAutomorphism",--this is a different way to compute a number field automorphism inverse that doesn't call M2's code, and just does linear algebra
   "asExtensionOfBase",--this probably shouldn't be exposed to the user long term
   "remakeField",--this probably shouldn't be exposed to the user long term
   "minimalPolynomial",
   "vectorSpace",
   --"ringMapFromMatrix",
   "isFieldAutomorphism",
   "isNumberField",
--    Maybe make this one internal?
   "polredbest",
   "galoisGroup",
   "isGNormal",
   "getAllSubgroups",
   "getNormalSubgroups",
   "fixedFields",
   "vectorToFieldEl",
   "fieldBaseChangeCharZero",
   "gp",
   "usePari"

   --"matrixFromRingMap"
};

global gp;
try (gp = findProgram("gp", "gp --version")) else (gp = null);
global defaultPariStrat;
defaultPariStrat = true;
if gp === null then {
    defaultPariStrat = false;
}
--NumberField = new Type of QuotientRing
NumberField = QuotientRing

-*
TempNumberField = new Type of QuotientRing

tempNumberField = method(Options => {Variable=>null})
tempNumberField(RingElement) := opts -> f1 -> (
    R1 := ring f1;
    if not isField coefficientRing R1 then error("Expected a polynomial over a field.");
    if #(gens R1) != 1 then error("Expected a polynomial in one variable.");
    if char R1 != 0 then error("Expected characteristic 0.");

    -- Verifies that the resulting quotient is a field.
    if f1 == 0 then error("Expected nonzero polynomial.");
    --if not isPrime ideal(f1) then error("Expected an irreducible polynomial.");

    tempNumberField(R1/ideal(f1), opts)
)



tempNumberField(Ring) := opts -> R1 -> (
    if R1===QQ then return new NumberField from {
            ring => R1, 
            pushFwd => pushFwd(map(QQ[],QQ)),
            cache => new CacheTable from {},
            String => "QQ, rational numbers"
        };
    
    if not isPrime (ideal 0_R1) then error("Expected a field.");
    if not dim R1 == 0 then error("Expected a field.");
    
    if char R1 != 0 then error("Expected characteristic 0.");
    outputRing := remakeField(R1, Variable=>opts.Variable);
    iota := map(outputRing,QQ);
    local myPushFwd;
    try myPushFwd = pushFwd(iota) else error("Not finite dimensional over QQ");
    genMinPolys := apply(gens outputRing, h->minimalPolynomial(h));

    genList := gens outputRing;
    genCt := #genList;
    i := 0;
    deg := degree outputRing;
    
    myStr := "Number Field, degree ";
    myStr = myStr | toString(deg) | " / Q, generated by:";
    if genCt == 0 then myStr = myStr + " nothing";
    while (i < genCt) do (
        myStr = myStr | " " | toString(genList#i) | " (" | toString (genMinPolys#i) | ")";
        i = i+1;
        if (i < genCt) then myStr = myStr | ", ";
    );

    tempNumField := new TempNumberField from outputRing;        

    tempNumField#pushFwd = myPushFwd;
    tempNumField#String = myStr;
    tempNumField#minimalPolynomial = genMinPolys;
    tempNumField#cache#degree = deg;

    tempNumField
)
*-

--
--The entries should be:
--ring (the ring it points to)
--cache (cached data)
--

--****************************
--NumberField constructors
--****************************

--The following function takes a ring and renames the variables
--in the future, it might also try to clean up relations (prune, trim, our own combination of prune/trim)
remakeField = method(Options => {Variable=>null, Degree => 1, NoPrune => false});
remakeField(Ring) := opts -> R1 -> (
    local var;
    local amb;
    local myIdeal;
    local finalRing2;
    a := local a;
    (R2, oldToNew, newToOld) := flattenRing(R1, Result=>3);
    
    if instance(R2, QuotientRing) then (amb = ambient R2; myIdeal = ideal R2) else (amb = R2; myIdeal = ideal(sub(0,R2)));
    numVars := #(gens amb);

    if opts.Variable === null then (var = a) else (var = opts.Variable);
    
    varList := {var_1..var_numVars};
    varDegrees := apply(numVars, i->opts.Degree);
    
    newRing1 := QQ(monoid[varList, Degrees=>varDegrees]);--we may want to think about the monomial order, we also might want to consider messing around with choosing a better presentation.
    
    phi := map(newRing1, amb, gens newRing1);
    finalRing := newRing1/phi(myIdeal);    
    psi := map(finalRing, R2, matrix phi);
    psiinv := inverse psi; 
    psi = psi*oldToNew;
    psiinv = newToOld*psiinv;
    
    if not opts.NoPrune then (
        finalRing2 = prune finalRing;
        psi = (finalRing.minimalPresentationMap)*psi;
        psiinv = psiinv*(finalRing.minimalPresentationMapInv);
    )
    else(
        finalRing2 = finalRing;
    );
    
    (finalRing2, psi, psiinv)
)

numberField = method(Options => {Verify => true, Verbose=>false, Variable=>null})
numberField(RingElement) := opts -> f1 -> (
    R1 := ring f1;
    if not isField coefficientRing R1 then error("Expected a polynomial over a field.");
    if #(gens R1) != 1 then error("Expected a polynomial in one variable.");
    if char R1 != 0 then error("Expected characteristic 0.");

    -- Verifies that the resulting quotient is a field.
    if f1 == 0 then error("Expected nonzero polynomial.");
    --if not isPrime ideal(f1) then error("Expected an irreducible polynomial.");

    numberField(R1/ideal(f1), opts)
)


-- Understand these better
numberField(Ring) := opts -> R1 -> (
    if opts.Verbose then print ("Starting NumberFieldConstructor, verifying validity :" | toString(opts.Verify));
    -*if R1===QQ then return new NumberField from {
            ring => R1, 
            pushFwd => pushFwd(map(QQ[],QQ)),
            cache => new CacheTable from {},
            String => "QQ, rational numbers"
        };*-
    local outputRing;
    local outputPsi;
    local outputPsiInv;
    if R1 === QQ then (
        --outputRing = new NumberField from QQ;
        outputRing = QQ[];
        outputRing#cache = new CacheTable from {};
        outputRing#cache#pushFwd = pushFwd(map(QQ[],QQ));
        outputRing#cache#String = "QQ, rational numbers";
    );
    
    if opts.Verify and not isPrime (ideal 0_R1) then error("Expected a field.");
    if opts.Verify and not dim R1 == 0 then error("Expected a field.");
    
    if opts.Verify and char R1 != 0 then error("Expected characteristic 0.");
    (outputRing, outputPsi, outputPsiInv) = remakeField(R1, Variable=>opts.Variable);
    iota := map(outputRing,QQ); 
    local myPushFwd;
    if opts.Verbose then (print "NumberFieldConstructor, computing pushFwd");    
    try myPushFwd = pushFwd(iota) else error("Not finite dimensional over QQ"); --we should check to see if the pushFwd has already been computed
    if not isFreeModule(myPushFwd#0) then error "numberField: something went wrong, this should be a free module over QQ";
    genMinPolys := apply(gens outputRing, h->minimalPolynomial(h));

    genList := gens outputRing;
    genCt := #genList;
    i := 0;
    deg := rank(myPushFwd#0);
        
    myStr := "Number Field, degree ";
    myStr = myStr | toString(deg) | " / Q, generated by:";
    if genCt == 0 then myStr = myStr | " nothing";
    while (i < genCt) do (
        --myStr = myStr | " " | toString(genList#i) | " (" | toString (genMinPolys#i) | ")";
        myStr = myStr | " (" | toString (genMinPolys#i) | ")";
        i = i+1;
        if (i < genCt) then myStr = myStr | ", ";
    );

    -*
    new NumberField from {
        ring => toField outputRing, 
        pushFwd => myPushFwd,
        String => myStr,
        minimalPolynomial => genMinPolys, --a list of min polys of gens, for display purposes
        cache => new CacheTable from {degree => deg}
    }
    *-    
    --tempNumField := new NumberField from outputRing;            
    tempNumField := outputRing;        
    tempNumField#cache#NumberField = true;
    tempNumField#cache#pushFwd = myPushFwd;
    tempNumField#cache#String = myStr;
    tempNumField#cache#minimalPolynomial = genMinPolys;
    tempNumField#cache#degree = deg;    
    tempNumField#cache#remakeField = (outputPsi, outputPsiInv);
    return tempNumField;
)

pushFwd(NumberField) := opts -> R1 -> (
    if isNumberField R1 or (R1#?cache and R1#cache#?pushFwd) then (
        return R1#cache#pushFwd;
    )
    else (
        iota := map(R1,QQ);
        if not R1#?cache then R1#cache = new CacheTable from {};
        myPush := pushFwd(iota);
        R1#cache#pushFwd = myPush;
        return myPush;
    );
);

--*****************************
--NumberField display
--*****************************

    -*
net NumberField := nf -> (

    myStr := "Number Field, degree ";
    myStr = myStr | toString(degree nf) | " / Q, generated by:";
    i := 0;
    genCt := #(gens ring nf);
    genList := gens ring nf;
    if genCt == 0 then myStr = myStr + " nothing";
    while (i < genCt) do (
        myStr = myStr | " " | toString(genList#i) | " (" | toString (nf#minimalPolynomial#i) | ")";
        i = i+1;
        if (i < genCt) then myStr = myStr + ", ";
    );
    --do some code
    

    nf#String
)
*-

--****************************
--NumberField basic operations
--****************************

-*ring(NumberField) := R1 -> (
    if (class (R1#ring) === PolynomialRing) then (
        return coefficientRing(R1#ring);
    );
    R1#ring
    varList := gens R1;
    myMon := monoid[varList];
    amb := QQ[varList];
    amb/sub(ideal R1, amb)
)*-




--degreeNF = method(Options => {})
degree(NumberField) := nf -> (
    if ( nf#cache#?NumberField ) then (
        if (nf#cache#?degree) then return nf#cache#degree;
        -*iota := map(ring(nf),QQ);
        rk := rank((pushFwd(iota))#0);
        nf#cache#degree = rk;
        rk*-
        --Karl:  something is wrong with pushFwd in this context, I rewrote this function for now.  The old version is above.
        return rank((pushFwd nf)#0);
    )
    else 
    (        
        return degree(nf^1);
    )
)

--this gives the basis for the numberField over QQ. Note this isn't used or exported anywhere.
basisOverQQ = method(Options=>{})
basisOverQQ(NumberField) := opts -> nf -> (
    first entries ((pushFwd nf)#1)
);

-- Check if this give the number field as a vectorspace over Q?
vectorSpace = method(Options=>{})
vectorSpace(NumberField) := opts -> nf -> (
    --nf#cache#pushFwd#0
    (pushFwd nf)#0
)

vector(RingElement, NumberField) := (f1, nf) -> (
    if not (ring f1 === nf) then error "Expected an element of the NumberField";
    ((pushFwd nf)#2)(f1)
);



--NumberFieldExtension = new Type of RingMap
NumberFieldExtension = RingMap

numberFieldExtension = method(Options => {})
numberFieldExtension(RingMap) := opts -> phi1 -> (
    answer := new NumberFieldExtension from phi1;
    answer#cache#String = ("Number field extension, degree " | degree answer);
    answer

    -*new NumberFieldExtension from {
        source=>numberField source phi1, 
        target=>numberField target phi1, 
        "map"=>phi1, 
        cache => new CacheTable from {}
    }*-
);

--net NumberFieldExtension := nfe -> (nfe#cache#String)
-- Unsure how this is used - Toshi
numberFieldExtension(RingElement) := opts -> f1 -> (
    if not (gens ring f1 == 1) then error "Expected a polynomial in a single variable";
    baseField := numberField coefficientRing ring f1;
);

--this only checks the flag.  In the future, we should maybe have this see if we can subclass ring to a number field
isNumberField = method(Options =>{});
isNumberField(Ring) := opts -> R1 -> (
    if R1#?cache then (
        if R1#cache#?NumberField then (
            return R1#cache#NumberField;
        )        
    );
    
    return false;
)

--this should give you the matrix over Q corresponding to a map of number fields.  
--It will throw an error if the map is not valid
matrixFromNumberFieldMap = method(Options=>{})
matrixFromNumberFieldMap(RingMap) := opts -> phi1 ->(    
    pushFwdSource := pushFwd source phi1;
    pushFwdTarget := pushFwd target phi1;
--    pushFwdMap := pushFwd phi1;
    outputList := apply( (first entries ((pushFwdSource)#1)), z -> (pushFwdTarget#2)(phi1(z)));
    
    fold((x,y)->x|y, outputList)
)

--source(NumberFieldExtension) := phi1 -> (source phi1);
--target(NumberFieldExtension) := phi1 -> (target phi1);
map(NumberFieldExtension) := opts -> phi1 -> (phi1);


degree(NumberFieldExtension) := nfe -> (
    if (nfe#cache#?degree) then return nfe#cache#degree;
    rk := rank((pushFwd(map(target nfe, source nfe, matrix nfe)))#0);
    nfe#cache#degree = rk;
    rk
)

-- Norm and Trace aren't used, but I do recall them being useful from number theory in Gordan's Class
norm(RingElement) := (elt) ->(
    S := ring elt;
    return det pushFwd(map(S^1, S^1, {{elt}}));
);
trace(RingElement) := (elt) -> (
    S := ring elt;
    return trace pushFwd(map(S^1, S^1, {{elt}}));
);
--*************************
--Methods
--*************************

isGalois = method(Options =>{})
-- I've added a isGalois function for number fields, though it could likely be optimized as it calls galoisGroup. (Toshi)
-- This is bad. We may want to have galoisGroup get the galois closure of a field first.
isGalois(NumberField) := opts -> (nF) -> (
    if length (galoisGroup(nF))_2 == degree nF then (
        return true;
    );
    return false;
)

-- isGalois(NumberFieldExtension) := opts -> iota -> (
--      myMapList := {}; --replace with Jack's function when ready
--     --assuming iota : K -> L, myMapList is a list of maps L -> L_i where 
--     --L_i is one of the components of L **_K L.
    
--     --check if all degrees are the same, and equal to 1.
-- )

isGalois(RingMap) := opts -> iota -> (
   isGalois(numberFieldExtension iota)
)

-- splittingField method
--****KARL:  THIS IS CURRENTLY BROKEN, I TRIED TO MAKE IT FASTER...*****
splittingField = method(Options => {Variable=>null, Verbose=>false})
splittingField(RingElement) := opts -> f1 -> (
    --R1 := QQ[x];    
    R1 := ring f1;
    if not (R1#?cache) then R1#cache = new CacheTable from {};
    if (R1#cache#?(splittingField,f1)) then 
    (   
        if opts.Verbose then print "splittingField: result already cached, returning";
        return R1#cache#(splittingField,f1);
    );
    curf1 := f1;
    curf1old := f1;
    varName := gens R1;
    if not (#varName == 1) then error "Expected a polynomial ring in a single variable";
    S1 := R1;
    Svar := (gens R1)#0;
    SvarOld := Svar;
    K1 := coefficientRing R1;
    K0 := K1;
    --K2 := (remakeField( coefficientRing R1, Degree=>0))#0;
    psi := map(K1, K1);
    totalPsi := psi;
    local psiInv;
    local unMadeField;
    local phi1;
    local linTerm;
    local finalAnswer;
    local flatTargetRing;
    local flatPsi;--psi should be the map that includes one field in another and sends x to x.
    local newPsi;
    local kappa;
    variableIndex := 1;
    finished := false;
    i := 1;
    idealList := {ideal curf1};
    L1 := flatten apply(idealList, z->decompose z);
    local var;
    a := local a;
    if opts.Variable === null then (var = a) else (var = opts.Variable);
    while not finished do (
        if debugLevel >= 5 then print ("Starting a loop : " | toString(idealList));        
        idealList = select(idealList, z->not isLinear z);        --let's only keep the good ones.
        --print i;
        --print curf1;
        if opts.Verbose then print idealList;
        i += 1;
        finished = true;
        --executeForLoop := true;
        if (#idealList > 0) then (
            curIdeal := idealList#0;
            currentEntry := (entries gens curIdeal)#0;   --grab a polynomial to work with
            finished = false;
            newTargetRing := K1[var_variableIndex, Degrees=>{0}];
            (flatTargetRing,flatPsi) = flattenRing(newTargetRing);
            newPsi = flatPsi*map(newTargetRing, S1, gens newTargetRing);
            kappa = map(S1, coefficientRing S1);
            K1 = flatTargetRing/newPsi(curIdeal);
            psi = (map(K1, target newPsi))*newPsi * kappa;
            -*unMadeField = R1/(idealList#0);
            totalPsi = (map(unMadeField, target totalPsi))  * totalPsi;
            (K1, psi) = flattenRing(K1[local a_variableIndex]);*-
            
            --(K1, psi) = remakeField (unMadeField, Degree=>0, NoPrune=>true);                    
            totalPsi = psi*totalPsi;
            --S1 = K1[local a_variableIndex];                    
            S1 = K1[varName];
            SvarOld = Svar;
            Svar = sub(varName#0, S1);
            linTerm = Svar - newPsi(SvarOld);
            phi1 = map(S1, R1, {Svar});    --this is behaving badly, let me try sub
            if debugLevel >= 5 then print phi1;               
            --curf1old = phi1(curf1);
            --curf1 = curf1old;-- // linTerm;      --is this working? --it is not.
            --assert(linTerm*curf1 == curf1old);
            
            idealList = drop(apply(idealList, z->sub(z, S1)), 1);
            if opts.Verbose then print "doing a saturate";
            newIdeal := saturate(sub(curIdeal, S1), linTerm);
            if opts.Verbose then print "checking isPrime";
            if debugLevel >= 5 then print newIdeal;
            if opts.Verbose then print "Starting a decompose";
            if (#idealList == 0) and (#currentEntry == 1) and (max degree(currentEntry#0) <= 2) then (
                    finished = true;
            ) 
            else (
                idealList = (decompose (newIdeal, Strategy=>"Legacy")) | idealList;
                R1 = S1;
                variableIndex += 1;
            )
        )

        
        -*for i from 0 to #idealList-1 do (
            if executeForLoop then (
                currentEntry := (entries gens L1#i)#0;         
                if opts.Verbose then print (toString(currentEntry) | " : " | toString(length(currentEntry)) | "," | toString(degree(currentEntry#0)) );
                if not (length(currentEntry)==1 and max(degree(currentEntry#0))==1) then (
                    finished = false;
                    unMadeField = R1/(L1#i);
                    totalPsi = (map(unMadeField, target totalPsi))  * totalPsi;
                    (K1, psi) = remakeField (unMadeField, Degree=>0);                    
                    totalPsi = psi*totalPsi;
                    --S1 = K1[local a_variableIndex];                    
                    S1 = K1[varName];
                    SvarOld = Svar;
                    Svar = sub(varName#0, S1);
                    linTerm = Svar - psi(SvarOld);
                    phi1 = map(S1, R1, {Svar});                    
                    curf1old = phi1(curf1);
                    curf1 = curf1old;-- // linTerm;      --is this working? --it is not.
                    --assert(linTerm*curf1 == curf1old);
                    R1 = S1;
                    variableIndex += 1;
                    executeForLoop = false;
                );                                
            );            
        );*-
    );
    --K1
    --numberField K1
    --numberFieldExtension map((flattenRing K1)#0[local y], R1)
    --numberFieldExtension (map(K1, K2))    
    (finalAnswer, psi, psiInv) = remakeField(K1, Degree=>1, Variable=>opts.Variable);

    answer := (numberField(finalAnswer, Verify=>false, Verbose=>opts.Verbose), numberFieldExtension(psi*totalPsi));    
    (ring f1)#cache#(splittingField,f1) = answer;
    answer
)

-- splittingField = method(Options => {Strategy=>null, usePari=>defaultPariStrat});
-- splittingField(RingElement) := opts -> p -> (
--     PARISIZE := 8000000;
--     setPariSize := n -> (PARISIZE = n);  
--     -- Code to not use gp when can't find. Maybe a global flag?
--     if usePari === false then{
--         return (p, 1);
--     };
--     -- Such code ends here to not use gp when can't find

--     R := ring p;
--     k := coefficientRing R;
--     d := (degree p)_0;
--     UID := temporaryFileName();
--     UID2 := temporaryFileName();
--     INPUT := UID|".gp";
--     OUTPUT := UID|"-output";
--     OUTPUT2 := UID2|"-output";
--     F := openOut INPUT;
--     F << "allocatemem("|toString PARISIZE|")\n"
--       << "[f,a]=polredbest("|toString p|", 1)\n"
--       << "for(d=0,poldegree(f),write1(\""|OUTPUT|"\",polcoeff(f,d),\",\"))\n"
--       << "write1(\""|OUTPUT2|"\",Vec(lift(a)),\",\")\n"
--      << "quit()" << close;
--     assert zero (runProgram(gp, "-q <"|INPUT))#"return value";
--     coeffs := value("{"|get OUTPUT|"}");
--     definingEl := toList(get OUTPUT2);
--     definingEl =drop(drop(definingEl,1),-2);
--     definingEl = concatenate definingEl;
--     definingEl = value("{"|definingEl|"}");
--     definingEl = reverse definingEl;
--     removeFile \ {INPUT, OUTPUT, OUTPUT2};
--     p1 := sum apply(d+1, i -> coeffs_i*R_0^i);
--     root := sum apply(length(definingEl), i -> definingEl_i*R_0^i);
--     -- root := sum apply(length(coeffsDefEl)-1, i -> coeffsDefEl_i*R_0^i);

--     return (p1,root );
-- );
-- Investigate - Toshi
isLinear = method(Options=>{})
isLinear(Ideal) := opts -> (J1) -> (
    if J1 == 0 then return true;
    idealGens := (entries gens J1)#0;
    length(idealGens)<=1 and max(degree(idealGens#0))<=1
)

-- Is this necessary?
syntheticDivision = method(Options=>{})
syntheticDivision(RingElement, RingElement) := (f1, g1) -> ( --compute f1 / g1, where g1 = x-a, and where g1 divides f1

)

-- Do we want to see if we can extend to isomorphic fields?
isFieldAutomorphism = method(Options=>{})
isFieldAutomorphism(NumberField, Matrix) := opts -> (NF1, sigma1) -> (
    R1 := NF1;
    C1 := coefficientRing R1;
    P1 := (pushFwd(map(R1, C1)))#2;
    phi1 := ringMapFromMatrix(NF1, sigma1);
    if not isWellDefined phi1 then (return false;);
    if not isInjective phi1 then (return false;);
    newBasis1 := apply(flatten entries basis NF1, i -> phi1(i));
    newGensAsBasis1 := apply(newBasis1, P1);
    A1 := newGensAsBasis1#0;
    for i from 1 to #newGensAsBasis1-1 do (
        A1 |= newGensAsBasis1#i;
    );
    return (A1-sigma1)==0 -- Test matrix equality only on entry level; A==sigma1 would return false if either sources or target differ
)

-- Helper method for isFieldAutomorphism
-*ringMapFromMatrix = method(Options=>{})

ringMapFromMatrix(NumberField, Matrix) := opts -> (NF1, sigma1) -> (
*-
-- Turns a matrix into a ringmap.
ringMapFromMatrix = (NF1, sigma1) -> (
    R1 := NF1;
    C1 := coefficientRing R1;
    P1 := (pushFwd(map(R1, C1)))#2;
    gensAsBasis1 := apply(gens R1, P1); -- Expresses each generator of R1 as a vector w.r.t. the basis of NF1
    newGensAsBasis1 := apply(gensAsBasis1, i -> sigma1*i);
    newGensAsMatrices1 := apply(newGensAsBasis1, i -> matrix(basis NF1)*i);
    newGens1 := apply(newGensAsMatrices1, i -> (entries i)#0#0);
    map(R1, R1, newGens1)
)
-*
matrixFromRingMap = method(Options=>{})

matrixFromRingMap(NumberField, RingMap) := opts -> (n1, psi) ->(
    print "Hello";
    matrixFromRingMap(n1, n1, psi)
)
matrixFromRingMap(ZZ,ZZ) := opts -> (i,j) -> (
    i+j
)

matrixFromRingMap(NumberField, NumberField, Thing) := opts -> (nf1, nf2, psi) -> (
*-
matrixFromRingMap = (nf1, nf2, psi) -> (
    if not ((target psi === ring nf1) and (source psi === ring nf2)) then error "expected the map to go from the the second argument to the first";
    
    B1 := basis nf2; --todo: we should use the pushFwd basis
    matrixOut := vector(psi(B1#0), nf1);
    i := 1;
    while (i < #B1) do (
        matrixOut = matrixOut | vector(psi(B1#i), nf1);
        i = i+1;
    );
    matrixOut
)
matrixFromRingEl = method(Options => {});
matrixFromRingEl(NumberField, RingElement) := opts -> (nF, rEl) -> (
    --R := ring nF;
--    R := nF;
--    return pushFwd(map(R^1, R^1, matrix{{rEl}}));
    matrixFromRingEl(rEl)
)
matrixFromRingEl(RingElement) := opts -> (rEl) -> (
    --R := ring nF;
    R := ring rEl;
    --return pushFwd(map(R^1, R^1, matrix{{rEl}}));
    p := pushFwd R;
    pf :=  p#2;
--    apply(first entries (p#1), z->pf(rEl*z));
    fold( (x,y)->x|y, apply(first entries (p#1), z->pf(rEl*z)))
)


ringElFromMatrix = method(Options => {Strategy=>"direct"});
ringElFromMatrix(NumberField, Matrix) :=opts -> (nF, mat) -> (
    --We basically turn the natural linear algebra basis of our number field into a matrix, then row reduce it to turn mat into an element in our number field.
    --R0 := ring nF;
    if opts.Strategy==="direct" then {
    R0 := nF;
    R1 := coefficientRing R0;
    M0 := (pushFwd(map(R0,R1)))_1;
    vList := {};
    for i from 0 to ((numgens source M0)-1) do(
        Mi := matrixFromRingEl(nF, (M0_i)_0);
        vi := vector reshape(R1^((numgens target Mi)*(numgens source Mi)), R1^1, Mi);
        vList = append(vList, vi);
    );
    vList = append(vList, vector reshape(R1^((numgens target mat)*(numgens source mat)), R1^1, mat));
    M := matrix(vList);
    RRM := reducedRowEchelonForm M;
    lastCol := RRM_{numColumns RRM-1};
    el := 0_R0;
    for i from 0 to ((numgens source M0)-1) do(
        el = el + (lastCol_0)_i * (M0_i)_0;
    );
    return el;
    }
    else if opts.Strategy === "solve" then {
        pf := pushFwd(nF);
    pfg := first entries (pf#1);
    --matrixListUnflat := apply(pfg, z->matrixFromRingEl(z));
    matrix2List := fold((a,b)->a|b, apply(pfg, z->transpose matrix{flatten entries matrixFromRingEl(z)}));
    mat2 := transpose matrix{flatten entries mat};
    soln := solve(matrix2List, mat2);
    --if not (matrix2List*soln == mat2) then error "ringElFromMatrix2: there is no solution, not a ring element";
    solnEntries := first entries transpose soln;
    --1/0;
    return sum(apply(#pfg, i -> (pfg#i)*(solnEntries#i) ))
    } 
)
--TODO:  Karl, we should try rewriting this function to use the Macaulay2 functionality "solve".  We should also throw an error if the answer is wrong.
-- ringElFromMatrix2 = method(Options => {});
-- ringElFromMatrix2(NumberField, Matrix) :=opts -> (nF, mat) -> (
--     pf := pushFwd(nF);
--     pfg := first entries (pf#1);
--     --matrixListUnflat := apply(pfg, z->matrixFromRingEl(z));
--     matrix2List := fold((a,b)->a|b, apply(pfg, z->transpose matrix{flatten entries matrixFromRingEl(z)}));
--     mat2 := transpose matrix{flatten entries mat};
--     soln := solve(matrix2List, mat2);
--     --if not (matrix2List*soln == mat2) then error "ringElFromMatrix2: there is no solution, not a ring element";
--     solnEntries := first entries transpose soln;
--     --1/0;
--     sum(apply(#pfg, i -> (pfg#i)*(solnEntries#i) ))
-- )
--huh, in my limited experimentation, this version is slower than the above

--this function should provide an alternate way to call inverse(RingMap) at least when the ring map is an isomorphism between two fields
--this function needs to be tested
inverseNumberFieldAutomorphism = method(Options => {});
inverseNumberFieldAutomorphism(RingMap) := opts -> (phi1) -> (
    R := source phi1;
    S := target phi1;
    SGensList := gens S;
    M := matrixFromNumberFieldMap(phi1);
    Mi := inverse M;
    RTargetList := apply(SGensList, z -> ringElFromMatrix(R, (Mi*(matrixFromRingEl z)*M)) );
    --apply(SGensList, z->matrixFromRingEl z)
    --RTargetList

--    RTargetList := apply(SGensList, z -> ringElFromMatrix(S, (Mi*(matrixFromRingEl z))) );
  --  RTargetList
--    apply(SGensList, z -> ringElFromMatrix(S, (matrixFromRingEl z)) );
    outputMap := map(R, S, RTargetList);
    outputMap    
)

--given a polynomial f in K[x] and a map K -> L, this forms the image of f in L[x].
polynomialFieldChange = method(Options => {});
polynomialFieldChange(RingElement, RingMap) := opts -> (f1,psi1) -> (
    coeffRing := coefficientRing ring f1;
    oldVars := gens ring f1;
    (myVars, myCoeffs) := coefficients f1;
    error "This is not finished yet.";
)
-- This gets the roots of a polynomial
getRoots = method(Options =>{Strategy=>decompose});
getRoots(RingElement) := opts -> (f1) -> (
    R1 := ring f1;
    if not (R1#?cache) then R1#cache = new CacheTable from {};
    -- For the cache, for each f1, should we store its roots in R1?
    -- if (nF#cache#?galoisGroup) then return nF#cache#galoisGroup;
    print(f1);
    linearTerms := {};
    local i;
    local newLinTerm;
    local newCoeffs;
    local newCoeffs2;
    local newVars;
    local newVars2;
    -- 1/0;
    if #(gens R1) != 1 then error "getRoots: expected a polynomial in a single variable";
    if opts.Strategy === decompose then (
        (S,M, MInv) := (flattenRing (R1,Result=>3));
        primeFactors := decompose ideal M(f1);
        
        for i from 0 to ((length primeFactors)-1) do(
            if (degree primeFactors#i_0)#0 == 1 then (
                -- This gets the multiplicative coefficient in front of 
                -- The prime factors will be linear terms that are of form Au - B where A,B are in the number field.
                -- Mycoeff is the A term, multCoef is 1/A. 
                -- We append to linear terms u-B/A
                myCoeff := (coefficients (MInv(primeFactors#i)_0))_1_0_0;
                multCoef := ringElFromMatrix (coefficientRing R1, inverse  (matrixFromRingEl (lift(myCoeff, coefficientRing R1)))) ;
                linearTerms = append(linearTerms, (gens R1)_0 - multCoef* MInv(primeFactors#i_0));
            );
        );
        return linearTerms;
    )
    else if (opts.Strategy === factor) then (
        K1 := ((flattenRing(coefficientRing R1))#0);
        (K2a, psi1) := simpleExtension(K1);
        psi2 := inverse psi1; --this is slow, it would be nice if it was faster
        (myVars, myCoeffs) := coefficients f1;
        K2 := toField K2a;
        R2 := K2[gens R1];
        myVars2 := sub(myVars, R2);
        myCoeffs2 := sub(psi2(sub(myCoeffs, K1)), R2);
        newf := first first entries (myVars2*myCoeffs2);
        tempTerms := factor newf;
        i = 0;
        while i <  #tempTerms do (
            if ((degree (tempTerms#i#0))#0 == 1) then (
                (newVars, newCoeffs) = coefficients tempTerms#i#0;
                newVars2 = sub(newVars, R1);
                newCoeffs2 = psi1(sub(newCoeffs, K2a));
                linearTerms = append(linearTerms, (gens R1)_0 - (entries(newVars2*newCoeffs2))#0#0);
            );
            i = i+1;
        );
        return linearTerms;
        --todo this needs to be written.newf
        --we should first find a way to 
        --error "getRoots:strategy=>factor not implemented yet";
    )
    else (
        error "getRoots: not a valid strategy";
    );
)

minimalPolynomial = method(Options => {Variable=>null})
minimalPolynomial(RingElement) := opts -> (f1) -> (--we should only compute the possible minimal polynomial degrees based on the degree
    -- if not(f1#?cache) then f1#cache = new CacheTable from {};
    -- if (f1#cache#?minimalPolynomial) then return f1#cache#minimalPolynomial;
    R1 := ring f1;        
    D := degree R1;
    local y;
    if (opts.Variable === null) then (y = local xx;) else (y = opts.Variable);    
    --y := local aa;
    S1 := (coefficientRing(R1))[y];
    y = (gens S1)#0;
    P1 := pushFwd(map(R1, coefficientRing(R1)));
    A1 := (P1#2)(1_R1);
    curf1 := 1;
    pow1 := 1;
    --while (gens(kernel(A1))==0) do (
    while ((pow1 == 1) and (gens(kernel(A1))==0)) or (D%(pow1-1) != 0) or (gens(kernel(A1))==0) do (
        if (debugLevel > 1) then print pow1;
        pow1 += 1;
        curf1=curf1*f1;
        --A1 = A1|(P1#2)(f1^pow1);
        A1 = A1|(P1#2)(curf1);
        if (pow1 > D+1) then error "minimalPolyommial: something went wrong, is this a field?";
    );
    pow1 = pow1-1;
    M1 := matrix({{1_S1}});
    for i1 from 1 to (pow1) do (
        M1 |= y^i1;
    );
    -- f1#cache#minimalPolynomial = (entries (M1*(gens(kernel(A1)))))#0#0;
    (entries (M1*(gens(kernel(A1)))))#0#0
)

minimalPolynomial(RingElement, RingMap) := opts -> (f1, psi1) -> (--this finds the minimal polynomial of an element f1 in L1, where the second argument is a field extension K1 -> L1 
    --
    R1 := ring f1;        
    R2 := target psi1;
    if not (R1 === R2) then error "minimalPolynomial: expected the target of the map to agree with the ring of the source";
    C1 := source psi1;
    D := (degree R1)/ (degree C1);
    local y;
    if (opts.Variable === null) then (y = local xx;) else (y = opts.Variable);    
    --y := local aa;
    S1 := C1[y];
    y = (gens S1)#0;
    P1 := pushFwd(psi1);
    A1 := (P1#2)(1_R1);
    curf1 := 1;
    pow1 := 1;
    --while (gens(kernel(A1))==0) do (
    while ((pow1 == 1) and (gens(kernel(A1))==0)) or (D%(pow1-1) != 0) or (gens(kernel(A1))==0) do (
        if (debugLevel > 1) then print pow1;
        pow1 += 1;
        curf1=curf1*f1;
        --A1 = A1|(P1#2)(f1^pow1);
        A1 = A1|(P1#2)(curf1);
        if (pow1 > D+1) then error "minimalPolyommial: something went wrong, is this a field?";
    );
    pow1 = pow1-1;
    M1 := matrix({{1_S1}});
    for i1 from 1 to (pow1) do (
        M1 |= y^i1;
    );
    (entries (M1*(gens(kernel(A1)))))#0#0
)

minimalPolynomial(List) := opts -> L1 -> (
    apply(L1, i -> minimalPolynomial(i))
)
--from rationalpoints2
-- This gets a "nicer" simple extension than the one we calculate.
polredbest = method(Options => {Strategy=>null, usePari=>defaultPariStrat});
polredbest(RingElement) := opts -> p -> (
    PARISIZE := 8000000;
    setPariSize := n -> (PARISIZE = n);  
    -- Code to not use gp when can't find. Maybe a global flag?
    if usePari === false then{
        return (p, 1);
    };
    -- Such code ends here to not use gp when can't find

    R := ring p;
    k := coefficientRing R;
    d := (degree p)_0;
    UID := temporaryFileName();
    UID2 := temporaryFileName();
    INPUT := UID|".gp";
    OUTPUT := UID|"-output";
    OUTPUT2 := UID2|"-output";
    F := openOut INPUT;
    F << "allocatemem("|toString PARISIZE|")\n"
      << "[f,a]=polredbest("|toString p|", 1)\n"
      << "for(d=0,poldegree(f),write1(\""|OUTPUT|"\",polcoeff(f,d),\",\"))\n"
      << "write1(\""|OUTPUT2|"\",Vec(lift(a)),\",\")\n"
     << "quit()" << close;
    assert zero (runProgram(gp, "-q <"|INPUT))#"return value";
    coeffs := value("{"|get OUTPUT|"}");
    definingEl := toList(get OUTPUT2);
    definingEl =drop(drop(definingEl,1),-2);
    definingEl = concatenate definingEl;
    definingEl = value("{"|definingEl|"}");
    definingEl = reverse definingEl;
    removeFile \ {INPUT, OUTPUT, OUTPUT2};
    p1 := sum apply(d+1, i -> coeffs_i*R_0^i);
    root := sum apply(length(definingEl), i -> definingEl_i*R_0^i);
    -- root := sum apply(length(coeffsDefEl)-1, i -> coeffsDefEl_i*R_0^i);

    return (p1,root);
);
-- We expect a list like {"2", "3", "4"} and this make the int 234.
listToInt = method(Options => {Strategy=>null});
listToInt(List) := opts -> (parser) -> (
    return sum apply(length(parser), i -> value(parser_i)*10^(length(parser)-i-1));
)

--Work in progress
compositumPari = method(Options => {Strategy=>null, usePari=>defaultPariStrat});

--Change these to number fields
--For now assume simple extensions, make them more general later
-- Need to add the proper morphisms from original into the compositum.
compositumPari(NumberField, NumberField) := opts -> (P, Q) -> (
    --We first get simple extensions for P and Q.
    if usePari === false  then{
        return (P,Q);
    };
    P1 := simpleExtension(P);
    Q1 := simpleExtension(Q);
    --
    PARISIZE := 8000000;
    setPariSize := n -> (PARISIZE = n);  
    -- k1 := coefficientRing P;
    -- k2 := coefficientRing Q;
    -- d1 := (degree ideal P)_0;
    -- d2 := (degree ideal Q)_0;
    UID := temporaryFileName();
    UID2 := temporaryFileName();
    UID3 := temporaryFileName();

    INPUT := UID|".gp";
    OUTPUT := UID|"-output";
    OUTPUT2 := UID2|"-output";
    OUTPUT3 := UID3|"-output";
    -- print(replace("a_1","x",toString (ideal P1_0)_0));
    F := openOut INPUT;
    -- F << "allocatemem("|toString PARISIZE|")\n"
    --   << "write1(\""|OUTPUT|"\",2,\",\")\n"
    --   << "quit()" << close;
    F << "allocatemem("|toString PARISIZE|")\n"
      << "L=nfcompositum(nfinit(a_1),"|replace("a_1","x",toString (ideal P1_0)_0)|", "|replace("a_1","x",toString (ideal Q1_0)_0)|", 1)\n"
      << "f = L[1][1]\n"
      << "for(d=0,poldegree(f),write1(\""|OUTPUT|"\",polcoeff(f,d),\",\"))\n"
      << "quit()" << close;
    assert zero (runProgram(gp, "-q <"|INPUT))#"return value";
        --   << "for(a=0,length(L),for(b=0,poldegree(L[a][1]),write1(\""|OUTPUT|"\",polcoeff(L[a][1],b),\",\")))\n"
    -- print("{"|get OUTPUT|"}");
    coeffs := value("{"|get OUTPUT|"}");
    -- print(coeffs);
    a := local a;
    R := QQ[a];
    d:= length(coeffs);
    -- print(R_0);
    -- print(d);
    -- coeffsDefEl := value("{"|get OUTPUT2|"}");
    -- print()
    -- print("{"|get OUTPUT|"}");
    -- print(get OUTPUT2);
    -- curList := toList(get OUTPUT2);
    -- curList =drop(drop(curList,4),-2);
    -- for i from 0 to length curList do {

    -- }
    -- curList = concatenate("{",,"}");
    -- definingEl:= concatenate(curList);
    -- print(definingEl);

    removeFile \ {INPUT, OUTPUT};
    return R/(sum apply(d-1, i -> coeffs_i*R_0^i));
    -- return (sum apply(d1+1, i -> coeffs_i*P_0^i),sum apply(length(coeffsDefEl)-1, i -> coeffsDefEl_i*0_0^i));
);

-- Gets simple extensions
simpleExtension = method(Options => {Strategy=>null, usePari=>defaultPariStrat});
simpleExtension(NumberField) := opts -> nf ->(
    --We first get the degree of K as a field extension over Q and store it as D. 
    --K := ring nf;
    if not(nf#?cache) then nf#cache = new CacheTable from {};

    if (nf#cache#?simpleExtension) then return nf#cache#simpleExtension;

    K := nf;
    D := degree K;
    --We find an element that produces a degree D field extension.
    d := 0;
    c := 0;
    local r;
    local h;
    local R1;
    local phi;
    local phi2;

    local simpleExt;
    local tempField;
    count := 0;
    primitiveElement := 0; -- Uncomment along with below chunk to get a simpler primitive element
    while d < D do 
    (
        -- Uncomment the following along with primitiveElement := 0 above to get a simpler primitive element
        (if primitiveElement==0 then (
            primitiveElement = sum gens K;
         )
        else if (count < 10) then (
            primitiveElement += (random(gens K))#0; -- Randomly shuffles the list of generators of K and then takes the first element
         )
         else (
            primitiveElement = random(1, K); -- Get a random homogeneous RingElement from K1 of degree 1
         )
        );
        r = primitiveElement;
        --

        if (opts.Strategy===kernel) then (
            aa := local aa;
            R1 = QQ[aa];
            phi = map( K, R1, {r});
            if  isPrime (kernel phi) then ( --we shouldn't do it this way
                I := kernel phi *sub (( 1/(((coefficients (first entries gens kernel phi)_0)_1)_0)_0), R1);
                tempField = R1/I;
                simpleExt = numberField(tempField, Verify=>false);                
                d = degree simpleExt;
--                if (d == D) then phi = (simpleExt#cache#remakeField)*(inverse map(K, tempField, {r}));
                if (d == D) then phi = (map(K, tempField, {r}))*((simpleExt#cache#remakeField)#1);
            );
        )
        else if (opts.Strategy===null) then (--I'm surprised that this is slower
            h = minimalPolynomial(r, Variable=> local aa);
            R1 = ring h;
            tempField = R1/(ideal h);
            simpleExt = numberField(tempField, Verify=>false);
            d = degree simpleExt;
--            if (d == D) then phi = (simpleExt#cache#remakeField)*(inverse map(K, tempField, {r}));            
            if (d == D) then phi = (map(K, tempField, {r}))*((simpleExt#cache#remakeField)#1);
        )
        else (
            error "simpleExt: invalid strategy";
        );
        count = count+1;
    );

    nf#cache#simpleExtension = (simpleExt, phi);
    if  not (opts.usePari === false) then{
        return (simpleExt, phi);
    };
    --Takes the simple extension given by our algorithm and runs polredbest on it.
    --Returns the pol to mod by and the a primitive root.
    -- print(((gens ideal(simpleExt))_0)_0);
    (p, root) := polredbest(((gens ideal(simpleExt))_0)_0);
    --Map from our ring into polredbest ring by sending a_1 to element
    phi2 = map((ring p) / p, source phi, {root} );
    nf#cache#simpleExtension = (numberField(tempField, Verify=>false), phi2*(inverse phi));
    --Invert phi and use this to construct a map from polredbestring to origRing.
    return ((ring p) / p , phi2*(inverse phi));
)

galoisGroup= method(Options => {Strategy=>null});
--Returns Permutations, corresponding roots, and galois group as matrix 
-- VERY SLOW!!!! Maybe integrate this with Pari?
galoisGroup(NumberField) :=  opts ->(nF) -> (
    if not(nF#?cache) then nF#cache = new CacheTable from {};
    if (nF#cache#?galoisGroup) then return nF#cache#galoisGroup;
    u := local u; 
    R1 := nF[u];
    numVars := length flatten entries basis  nF;
    x := local x;
    --We get all the roots and store them in rootList
    rootList := {};
    
    for i from 0 to (length gens coefficientRing R1)-1 do(
        r0 := (gens coefficientRing R1)_i;
        minPol := minimalPolynomial(r0);
        M0 := map(R1,ring minPol,{(gens R1)_0});
        -- print ring minPol;
        print getRoots(M0(minPol));

        rootList = append(rootList, getRoots(M0(minPol)));
    );
    -- print M0;
    --We then generate the necessary permutations.
    perms := toList (0..(length rootList_0 - 1));
    for i from 1 to length rootList - 1 do (
        perms = perms ** toList (0..(length rootList_i - 1));
    );
    if length rootList == 1 then (
        perms = {};
        for i from 0 to length rootList_0 -1 do (
            perms = append(perms, {i})
        );
    );
    perms = perms / splice;
    --We then loop through, checking if they are field automorphisms, then adding them to all maps if they are.
    allMaps := {};
    allRingMaps := {};
    curGroup := {};
    for i from 0 to length perms -1 do (
        rootsImg := {};
        for j from 0 to length perms_i -1 do (
            rootsImg = append(rootsImg, substitute(rootList_j_(perms_i_j), nF));
        );
        M := map(nF, nF, rootsImg );
        
        F := matrixFromNumberFieldMap(M);
        flag := false;
        if opts.Strategy === "strat2" then (
            if any(curGroup, g -> g == F ) then(
                flag = true;
            )
        );
        if flag then (

        )
        else if isFieldAutomorphism(nF, F) then (
            allMaps = append(allMaps, F);
            allRingMaps = append (allRingMaps, M);
            if opts.Strategy === "strat2" then (
                curGroup = group finiteAction(allMaps, QQ [x_1..x_numVars]);
            );
        );
    );
    --We then create the group
    --We need to use root list ordering to create a permutation representation of galois group. This will be slow but memory good
    --We currently have the map applying to variable correctly.
    allPerms := {};
    for i from 0 to length allMaps-1 do (
        curPerm := {};
        for j from 0 to length flatten rootList -1 do (
            -- We build permutations by checking how the ring map acts on each root of the list.
            curPerm = append (curPerm,1+ position(flatten rootList, a ->  a== allRingMaps_i(lift ((flatten rootList)_j, coefficientRing ring (flatten rootList)_j)))); 
        );
        p:= permutation curPerm;
        -- print p;
        -- print (p*{0, 1, 2});
        allPerms = append(allPerms, curPerm);
        -- print ring allMaps_i;
        -- print allRingMaps_i(lift (rootList_0_0, coefficientRing ring rootList_0_0));
        -- print ring lift (rootList_0_0, coefficientRing ring rootList_0_0);
    );
    -- print(allMaps);
    -- print allPerms;
    nF#cache#galoisGroup = (allPerms, flatten rootList, group finiteAction(allMaps, QQ [x_1..x_numVars]));
    return (allPerms, flatten rootList, group finiteAction(allMaps, QQ [x_1..x_numVars]));
)

-- This implementation is for if a user has used "toField" on a numberField object...
galoisGroup(PolynomialRing) :=  opts ->(K) -> (
    -- We get the coefficient ring of K and return the corresp number field's galois group. 
    if isNumberField coefficientRing K then(
        return galoisGroup(coefficientRing K)
    );
    return 

)

-- Let us have a numberfield. Take the vectorspace structure over Q it possesses. 
-- Convert the vector using the basis of the generators of nF to a NF element.
vectorToFieldEl = method(Options =>{});
vectorToFieldEl(NumberField, Vector) := opts -> (nF, v) -> (
    b := flatten entries basis nF;
    el := 0_nF;
    for i from 0 to (length  b) -1 do (
        el = el + b_i * v_i;
    );
    return el;
);

isGNormal = method(Options =>{});
isGNormal(List, List) :=  opts -> (G, H) ->(
    conj := null;
    for i from 0 to length H -1 do (
        --We conjugate each element of H by each element of G, if any aren't in H, then not normal, otherwise noraml
        for j from 0 to length G - 1 do (
            conj = G_j * H_i * (inverse G_j);
            if not any(H, h -> h == conj) then (
                return false;
            );
        );
    );
    return true;
)
-- Gets all subgroups given the matrices of a Galois group
-- Todo: Make it work for different representations 
getAllSubgroups = method(Options =>{});
getAllSubgroups(List) := opts -> (G) -> (
    x := local x;
    numVars := length flatten entries G_0_0;
    allSubgroups := set {};
    curSubsets := null;
    --We only need to look at half
    for i from 1 to ceiling (length G/2) do (
        curSubsets = subsets(G, i);
        for j from 0 to length curSubsets - 1 do(
            allSubgroups = allSubgroups + set{set(group finiteAction(curSubsets_j, QQ [x_1..x_numVars]))};
        );
    );
    allSubgroupList := {};
    for i from 0 to length (toList allSubgroups) - 1 do (
        allSubgroupList = append(allSubgroupList, toList (toList allSubgroups)_i);
    );
    return allSubgroupList;
);
-- We can get this with Pari
getNormalSubgroups = method(Options =>{});
getNormalSubgroups(List) := opts -> (G) -> (
    normalGroups := {};
    allSubgroups := getAllSubgroups(G);
    for i from 0 to length allSubgroups -1 do (
        if isGNormal(G, allSubgroups_i) then(
            normalGroups = append(normalGroups, allSubgroups_i); 
        );
    );
    return normalGroups;
);
-- Gets all the fixed fields of a numberField.
-- We can integrate this with Pari
fixedFields = method();
fixedFields(NumberField) := (nF) -> (
    if not(nF#?cache) then nF#cache = new CacheTable from {};
    if (nF#cache#?fixedFields) then return nF#cache#fixedFields;
    G := null;
    G = (galoisGroup(nF))_2;
    NG := null; --have to write this function; should return a list of normal 
    --   subgroups of G(these groups are lists of matrices).
    NG = getNormalSubgroups(G);
    allFixed := {};
    H := null;
    allFixedVectors := null;
    idMatrix := id_(source( NG_0_0));
    allMinPoly := set {};
    aa := local aa;
    testRing := QQ[aa];
    numCols := null;
    M := null;
    v := null;
    p := null;
    x := local x;
    relationIdeal := null;
    ambientRing := null;
    for i from 0 to length NG -1 do (

        H = NG_i;
        if length H ==1 then (
            allFixed = append(allFixed, nF);
        )
        else(
            -- We calcualate the intersection of fixed vectors in normal subgroup H 
            allFixedVectors = kernel (H_0 - idMatrix);
            for j from 1 to length H -1 do (
                allFixedVectors = intersect(allFixedVectors, kernel (H_j - (idMatrix)) );

            );
            --We create the set of all minimalpolynomials of fixedVectors
            --We do so with set so we don't have duplicate min polynomials
            allMinPoly = set {};
            numCols = numColumns basis allFixedVectors; --Assuredly a better way of indexing; ask Karl.
            for j from 0 to numCols -1 do (
                v = vectorToFieldEl(nF, allFixedVectors_j);
                p = minimalPolynomial v;
                M = map(testRing,ring p,{(gens testRing)_0});
                allMinPoly = allMinPoly + set {M(p)};
            );
            -- We now create a base ring and quotient out by each minimal polynomial
            allMinPoly = toList allMinPoly;
            numVars := length allMinPoly;
            ambientRing = QQ[x_0..x_(numVars-1)];
            relationIdeal = ideal(0_ambientRing); 
            for j from 0 to numVars -1 do (
                M = map(ambientRing,ring allMinPoly_j,{(gens ambientRing)_j});
                relationIdeal = relationIdeal + M(allMinPoly_j);
            );
            allFixed = append(allFixed, numberField(ambientRing/relationIdeal));
        );
        --We create a ring with indeterminates for each min polynomial in allMinPoly, then add the field that is this ring mod all the min polynomials

    );
    nF#cache#fixedFields = allFixed;
    return allFixed;
)

--********************************
--******Compositums
--********************************

-- asExtensionOfBase = method(Options => {})
-- asExtensionOfBase(NumberFieldExtension) := opts -> iota -> (
-- --
-- --    -- get source and target
-- --    s := ring(source iota);
-- --    t := ring(target iota);
-- --    -- get ideal from target
-- --    --I := ideal target; 
-- --    -- calculate numgens of ideal
-- --    n := numgens t;
-- --    -- create polynomial ring in numbgens variables
-- --    polyring := s[b_1..b_n];
-- --    -- create map by assigning generators to other generators
-- --    extensionMap := map(iota);
-- --    images := (entries  (matrix extensionMap))#0;
-- --    m := map(t,polyring,join(images, gens(t)));
-- --    -- take the kernel
-- --    k := kernel m;
-- --    -- return quotient by kernel
-- --    polyring / k
-- )

--loadPackage ("NumberFields", Reload=>true)

-- takes a number field and a map to the original ring used to create
-- the number field, and returns the map composed with the isomorphism
composedMap = method(Options => {})
composedMap(NumberField,Ring) := opts -> (nf,S) -> (

  Psi := nf#cache#remakeField#0;
  R := source(Psi);
  G := map(R,S);
  return Psi*G;

)

-- note: add basic case when degrees are relatively prime
compositums = method(Options => {})
compositums(NumberField,NumberField) := opts -> (K1,K2) -> (
    
    T := K1 ** K2;
    if (gcd(degree K1, degree K2) == 1) then (
        numfld := numberField(T);
        return { (numfld,map(T, K1), map(T, K2),degree numfld) };
    );
    -- compositums correspond to prime ideals
    II := decompose (ideal 0_T);
    -- quotient rings
    QRs := apply(II, I -> T / I);
    -- make them number field objects?
    NFs := apply(QRs, qr -> numberField(qr));
    -- sort by degree
    sorted := sort(NFs, degree);
    -- get maps from K1 & K2 
    K1maps := apply(sorted, nf -> composedMap(nf,K1));
    K2maps := apply(sorted, nf -> composedMap(nf,K2));

    degs := apply(sorted, degree);
    -- a slight hack to package the data
    inds := toList(0..(length(sorted)-1));
    infoList := apply(inds, i -> (sorted#i,K1maps#i,K2maps#i,degs#i));

    infoList
)

compositums(NumberFieldExtension,NumberFieldExtension) := opts -> (iota,kappa) -> (
    -- check for common base
    b1 := source iota;
    b2 := source kappa;
    if not (class b1 === class b2) then error "the sources of the two extensions have different types, but they must match";
    if (class b1 === QuotientRing) then (
        if not (ideal b1 == ideal b2) then error "the sources of the two extensions must match";
    );

    K1 := target iota;
    K2 := target kappa;
    T := K1 ** K2;

    if (gcd(degree iota, degree kappa) == 1) then (
        mapT := map(T,b1);
        extn := numberFieldExtension(mapT);
        return { (extn,map(T, target iota), map(T, target kappa),degree extn) };
    );
    -- compositums correspond to prime ideals
    II := decompose (ideal 0_T);
    -- quotient rings
    QRs := apply(II, I -> first flattenRing(T / I, CoefficientRing=>b1));
    -- make them number field objects?
    NFs := apply(QRs, qr -> numberFieldExtension(map(qr,b1)));
    -- sort by degree
    sorted := sort(NFs, degree);
    -- get maps from K1 & K2 
    K1maps := apply(sorted, nfe -> map(target(nfe),K1));
    K2maps := apply(sorted, nfe -> map(target(nfe),K2));

    degs := apply(sorted, degree);
    -- a slight hack to package the data
    inds := toList(0..(length(sorted)-1));
    infoList := apply(inds, i -> (sorted#i,K1maps#i,K2maps#i,degs#i));
    infoList

)

--****************************
--SwitchingFields overloads
--****************************

fieldBaseChangeCharZero = method(Options=>{})
fieldBaseChangeCharZero(Ring, Ring) := opts -> (R1, K1) -> (

);

fieldBaseChangeCharZero(Ring, RingMap) := opts -> (R1, K1) -> (

);

--*****************************
--Documentation
--*****************************
beginDocumentation()

doc ///
    Key
        NumberFields
    Headline
        number fields and Galois theory
    Description
        Text
            {\em NumberFields} is a package that allows for clean definition and use of number fields. A number field is a extension of $\QQ$ of finite degree, e.g., $\QQ(\sqrt(2))$, which is isomorphic to $\QQ[x]/(x^2-2)$.
///

doc ///
    Key
        ringElFromMatrix
        (ringElFromMatrix, NumberField, Matrix)
    Headline
        Given an (invertible) matrix over a number field viewed as a vectorspace over \mathbb{Q}, output the corresponding ring element whose action is that matrix.
    Usage
        g = ringElFromMatrix (NF, M)
    Inputs
        NF: NumberField
            The numberfield in which we the ring element we convert to will live.
        M: Matrix
            The matrix we convert to a ring element.
    Outputs
        g: RingElement
            The ring element whose action is M over the numberfield viewed as a vectorspace over \mathbb{Q}
    Description
        Text
            This function takes a numberfield and an (invertible) matrix and outputs the element in the numberfield whose action is the matrix. If no such element exists, output 0(Maybe do different?).
        Example
            NF = numberField( QQ[x]/(x^2-2))
            M = matrix{{0,2/1},{1,0}} -- Viewing numberfield as [a,b] where a is QQ coordinate and b is \sqrt{2} coordinate, this matrix corresponds to the action of multiplying by \sqrt{2}
            a = ringElFromMatrix(NF, M)
            -- We see that a is the indeterminate in NF, thus corresponds to \sqrt{2}.

///

-- -- (matrixFromRingEl, NumberField, RingElement) seems pointless...

doc ///
    Key
        matrixFromRingEl
        (matrixFromRingEl, RingElement)
        (matrixFromRingEl, NumberField, RingElement) 

    Headline
        Given a ring element in a numberField, output it's action as a matrix when thinking of the numberField as a vectorspace over \mathbb{Q}
    Usage
        M = matrixFromRingEl (r1)
        M = matrixFromRingEl (NF, r1)

    Inputs
        NF: NumberField
            The numberfield in which the ring element lives.
        r1: RingElement
            The ring element we wish to convert
    Outputs
        M: Matrix
            A matrix over \mathbb{Q} that represents the action of the r1.
    Description
        Text
            This function calculates the matrix over \mathbb{Q} that represents the action of multiplication by r1 in the nubmerfield. We think of this matrix as an action over the numberfield viewed as a vectorspace.
        Example
            NF = numberField( QQ[x]/(x^2-2))
            r1 = (gens NF)#0 --This corresponds to \sqrt(2) in NF
            M = matrixFromRingEl(r1)
///

doc ///
    Key
        splittingField
        (splittingField,RingElement)
    Headline
        creates the splitting field of a polynomial
    Usage
        splittingField f
    Inputs
        f: RingElement
            a polynomial whose splitting field the method returns
    Outputs
        : NumberFieldExtension
    Description
        Text
            This method creates a @TO NumberFieldExtension@ whose source is $\mathbb{Q}$, target is a NumberField consisting of the splitting field of $f$, and map is inclusion. Recall that the splitting field of a polynomial $f$ with coefficients in a field $\FF$ is the smallest field extension of $\FF$ in which $f$ splits, or factors into linear factors.
        Example
            R = QQ[x];
            f = x^2-2;
            splittingField f
            f = x^2+x+1;
            splittingField f
///

doc ///
    Key
        minimalPolynomial
        (minimalPolynomial, RingElement)
        (minimalPolynomial, List)
    Headline
        computes the minimalPolynomial of a field element or list of field elements
    Usage
        g = minimalPolynomial f
        L1 = minimalPolynomial L
    Inputs
        f: RingElement
            the polynomial whose minimal polynomial the method computes
        L: List
            a list of polynomials whose minimal polynomials the method computes
    Outputs
        g: RingElement
            minimal polynomial
        L1: List
            list of minimal polynomials
    Description
        Text
            This method computes minimal polynomials. Recall that if $\mathbb{K}$ is a field extension of $\mathbb{F}$, the minimal polynomial of a field element $\alpha$ in $\mathbb{K}$ is, if it exists, the unique monic polynomial $f$ of lowest degree with coefficients in $\mathbb{F}$ such that $\alpha$ is a root of $f$.
        Example
            R = QQ[x]/(x^3-2);
            f = x;
            g = minimalPolynomial f
            L = {x, x^2, x^2+x};
            L1 = minimalPolynomial L
///

doc ///
    Key
        galoisGroup
        (galoisGroup, NumberField)
    Headline
        computes the Galois Group of a number field.
    Usage
        G = galoisGroup NF
    Inputs
        NF: NumberField
            the number field whose galois group the method computes.
    Outputs
        permsList: RingElement
            minimal polynomial
        rootList: List
            list of roots that give an ordering for the roots that the permsList permutes
        groupMatrices: List
            list of matrices that represent the action of each element of the group element as a permutation matrix. Respects the ordering from rootList
    Description
        Text
            This method computes galois group of $\mathbb{K}$ a  field extension of $\mathbb{Q}$. If the $\mathbb{K}$ isn't galois, then we take the galois closure of $\mathbb{K}$.
        Example
            R = QQ[w,v]/ ideal(w^3-2,v^2+v+1)
            NF = numberField(R)
            galoisGroup NF
///

doc ///
    Key
        simpleExtension
        (simpleExtension, NumberField)
    Headline
        Given a NumberField, computes a simple extension. If the user has Pari, then runs Pari to create a nicer simple extension.
    Usage
        (S, phi) = simpleExtension nF
    Inputs
        nF: NumberField
            the number field whose galois group the method computes.
    Outputs
        S: NumberField
            The simpleExtension related to NF
        phi:
            The isomorphism from NF to S.
    Description
        Text
            This method computes a simple extension of $NF := \mathbb{Q}[x_1,...,x_n]$, as well as a map phi such that phi:NF -> S.
        Example
            R = QQ[w,v]/ ideal(w^3-2,v^2+v+1)
            NF = numberField(R)
            simpleExtension NF
///
-- Should we include the injection morphisms for the numberField into the top field? 
-- Should we include details relating to the coressponding normal subgroup?
-- Note lots of our group operations are factorial which is suboptimal
doc ///
    Key
        fixedFields
        (fixedFields, NumberField)
    Headline
        Given a NumberField, computes all of the fixed fields.
    Usage
        F = fixedFields NF
    Inputs
        NF: NumberField
            the number field which we find the fixed fields of.
    Outputs
        F: List
            A list of number fields that are fixed by NF
    Description
        Text
            This method takes a number field and finds all the fixed fields. We first calculate the galois group, 
            then we take all the normal subgroups. For each of these, we construct the fixed field by looking at the
            eigenvectors(fixed field elements!) of the normal subgroup. We then throw these into our list.
        Example
            R = QQ[w,v]/ ideal(w^3-2,v^2+v+1)
            NF = numberField(R)
            fixedFields NF 
///

doc ///
    Key
        getRoots
        (getRoots, RingElement)

    Headline
        Given a polynomial over one indeterminant, output all of its roots.
    Usage
        L = getRoots (p)
    Inputs
        p: RingElement
            We expect p to be a polynomial in a polynomial ring with one indeterminant. Note the coefficient ring could be another polynomial ring, this is fine.
    Outputs
        L: List
            All the roots of p.
    Description
        Text
            This function gives all the roots of a polynomial, p, in one indeterminant. We assume the polynomial splits completely in the coefficient ring.
        Example
            NF = numberField( QQ[x]/(x^2-2))
            R1 = NF[u]
            p = minimalPolynomial (gens NF)#0 --This gives minimal polynomial over \mathbb{Q}[x]
            M0 = map(R1,ring p,{(gens R1)_0}); --We use this to convert this min poly into one over NF[u] (relabel x into u)
            M0(p)
            getRoots(M0(p))
///
doc ///
    Key
        getNormalSubgroups
        (getNormalSubgroups, List)
    Headline
        Given a group, finds all of its subgroups. This is in general expensive
    Usage
        AllH = getNormalSubgroups G
    Inputs
        G: List
            A list of matrices defining a group.
    Outputs
        AllH: List
            A list of subgroups of G.
    Description
        Text
            Takes all subgroups of a group. Both the group and its subgroups are represented as lists.
        Example
            R = QQ[w,v]/ ideal(w^3-2,v^2+v+1)
            NF = numberField(R)
            G = galoisGroup NF
            allH = getNormalSubgroups G#2  
///
--*****************************
--Tests
--*****************************

TEST /// --Test #0
    K = QQ[x]/ideal(x^3-2)
    L = K[y]/ideal(y^2 + y + 1)
    assert(degree numberField K == 3)
    assert(degree numberField L == 6)
///

--this simply checks whether the pushFwd functionality is working
TEST /// --Test #1
    R = QQ[x]/(x^4-3);
    p1 = pushFwd R;
    assert(rank (p1#0) == 4);
    nf = numberField R
    assert (isNumberField nf)
    p2 = pushFwd nf
    assert(rank (p2#0) == 4)
///

--this checks matrixFromNumberFieldMap
TEST /// --Test #2
    R = QQ[a]/ideal(a^3-2)
    S = QQ[b]/ideal((b+1)^3-2)
    h = map(S, R, {b+1})
    assert(isWellDefined h)
    p1 = pushFwd R
    p2 = pushFwd S
    assert (p1#1 == matrix{{1,a,a^2}})
    assert (p2#1 == matrix{{1,b,b^2}})
    M = matrixFromNumberFieldMap(h)
    assert(M == matrix{{1/1,1,1}, {0,1,2},{0,0,1}})
    g = inverse h
    N = matrixFromNumberFieldMap(g)
    assert(M*N == matrix{{1/1,0,0},{0,1,0},{0,0,1}})
///

--this also checks matrixFromNumberFieldMap
TEST /// --Test #3
    R = QQ[a,b]/ideal(a^3-2, a^2+a*b+b^2)
    h = map(R, R, {b,a})
    p1 = pushFwd R    
    g = inverse h
    M = matrixFromNumberFieldMap(h)
    N = matrixFromNumberFieldMap(g)
    assert(M*N == id_(QQ^6))
///

--this checks "matrixFromNumberFieldMap", "ringElFromMatrix","matrixFromRingEl"
TEST /// --Test #4
    R = numberField(QQ[a]/ideal(a^4+a^3+a^2+a+1))
    b = (gens(R))#0
    h3 = map(R, R, {b^3})
    assert(isWellDefined h3)
    c = matrixFromRingEl(R, b^2)
    M = matrixFromNumberFieldMap(h3)
    Mi = inverse M
    d = ringElFromMatrix(R, M*c*Mi)
    assert(d == h3(b^2))
    x = random(1, R) + random(2,R)+random(3,R) + random(4,R)
    cx = matrixFromRingEl(R, x)
    dx = ringElFromMatrix(R, M*cx*Mi)
    assert(dx == h3(x))
///
TEST /// --Test #5
    assert(0 == 0)
///
-- Tests 6-8 are to check if simple extension is working correctly. We test using Pari and not using Pari
TEST /// --Test #6
    R = numberField (QQ[a,b]/ideal(a^4+a^3+a^2+a+1, b^2+1))
    S = simpleExtension R 
    assert(isSurjective  matrixFromNumberFieldMap S#1)
    assert(isInjective  matrixFromNumberFieldMap S#1)

///
TEST /// --Test #7
    R = numberField (QQ[a,b]/ideal(a^4+a^3+a^2+a+1, b^2+1))
    S = simpleExtension (R, usePari=>false) 
    assert(isSurjective  matrixFromNumberFieldMap S#1)
    assert(isInjective  matrixFromNumberFieldMap S#1)
///
TEST /// --Test #7
    R = numberField (QQ[a]/ideal(a^2+1))
    S = simpleExtension (R) 
    assert(isSurjective  matrixFromNumberFieldMap S#1)
    assert(isInjective  matrixFromNumberFieldMap S#1)
///
TEST /// --Test #8
    R = numberField (QQ[a]/ideal(a^2+1))
    S = simpleExtension (R, usePari=>false) 
    assert(isSurjective  matrixFromNumberFieldMap S#1)
    assert(isInjective  matrixFromNumberFieldMap S#1)
///
-*TEST /// --Test #1
    K = QQ[x]
    f = x^2-2
    assert( isIsomorphic(target splittingField(f), numberField(QQ[y]/(y^2-2))) )
///


-*
This is a comment block.
*-
end
