name: Project Testbot

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-bot:
    name: Testing ${{ github.head_ref || github.ref_name }}
    runs-on: macos-13

    steps:
      - name: Checkout the project repository
        uses: actions/checkout@v4

      - name: Installing M2 via Homebrew
        run: |
          brew install macaulay2/tap/M2

      - name: Building ComputeGV
        run: |
          make -C ComputeGV

      - name: Testing computeGV
        run: |
          cd ComputeGV
          ./computeGV < example_input_3fold_hyper.txt
