name: Project Testbot

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-bot:
    name: Testing ${{ github.head_ref || github.ref_name }}
    runs-on: ubuntu-latest
    container:
      image: 'ghcr.io/macaulay2/testbot:latest'
      volumes:
        - '${{ github.workspace }}:/home/macaulay'

    steps:
      - name: Checkout the project repository
        uses: actions/checkout@v2

      - name: Run testbot on project branch
        run: |
          M2 --stop --no-debug --silent < tests/testbot.m2
